/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayWorldIdRouteImport } from './routes/play/$worldId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayWorldIdRoute = PlayWorldIdRouteImport.update({
  id: '/play/$worldId',
  path: '/play/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$worldId': typeof PlayWorldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$worldId': typeof PlayWorldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$worldId': typeof PlayWorldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$worldId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$worldId'
  id: '__root__' | '/' | '/play/$worldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayWorldIdRoute: typeof PlayWorldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$worldId': {
      id: '/play/$worldId'
      path: '/play/$worldId'
      fullPath: '/play/$worldId'
      preLoaderRoute: typeof PlayWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayWorldIdRoute: PlayWorldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
